# Generated by Django 5.1.3 on 2024-12-22 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_command'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sensordata',
            old_name='sensor_value',
            new_name='sensor_value_1',
        ),
        migrations.AddField(
            model_name='sensordata',
            name='sensor_value_2',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sensordata',
            name='sensor_value_3',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
